# Generated by Django 5.0.6 on 2024-07-07 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qrgenerator', '0002_delete_qrcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCodeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code_data', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
